### PR TITLE
feat(airflow): Add s3fs python package, needed for pandas S3 access

### PR DESCRIPTION
**Pull request by sbernauer**
# Description

*Please add a description here.*

## Definition of Done Checklist

- Not all of these items are applicable to all PRs, the author should update this template to only leave the boxes in that are relevant
- Please make sure all these things are done and tick the boxes
 
```[tasklist]
- [ ] Changes are OpenShift compatible
- [x] All added packages (via microdnf or otherwise) have a comment on why they are added
- [ ] Things not downloaded from Red Hat repositories should be mirrored in the Stackable repository and downloaded from there
- [ ] All packages should have (if available) signatures/hashes verified
- [ ] Does your change affect an SBOM? Make sure to update all SBOMs
```

This enables us to e.g.
```
    @task
    def write_repos_to_s3(df: pandas.DataFrame):
        staging_table_name =''.join(random.choice(string.ascii_lowercase) for i in range(32))
        df.to_parquet(
            f"s3://{S3_BUCKET}/staging/github/{staging_table_name}/repos.parquet",
            storage_options={
                "key": S3_ACCESS_KEY_ID,
                "secret": S3_SECRET_ACCESS_KEY,
                "client_kwargs": {'endpoint_url': S3_ENDPOINT}
            }
        )
        return staging_table_name
```

### CODE REVIEW

**Comment by lfrancke** [comment]
Also see here 
https://github.com/stackabletech/docker-images/pull/411/files :)

**Comment by sbernauer** [comment]
I was thinking about the same, but I did not want to clog up the Dockerfile, so I put the reason in the commit message ;)
Added it to Dockerfile as well

**Comment by sbernauer** [comment]
Hmm, if think technically I can't check the other boxes. Do we want to make some exceptions for pip? Is there any guide regarding the boms yet?

**Review by lfrancke — APPROVED** [review]

**Comment by lfrancke** [comment]
No SBOM guide yet. I'm working on that.

So, this will need to change again but good enough for now

**Comment by lfrancke** [comment]
As always. Those are just templates. Leave the boxes that make sense, remove the others.

I think this is good to go. I'm only on my phone but I believe I approved it as well

**Comment by sbernauer** [comment]
Yeah you did, thanks!

**Pull request merged**
