### PR TITLE
feat(hbase): Add dependencies for ABFS and ADLS

### PR DESCRIPTION
**Pull request by siegfriedweber**
# Description

Add hadoop-azure.jar to the lib directory to support the Azure Blob Filesystem and the Azure Data Lake Storage.

required by stackabletech/hbase-operator#539

## Definition of Done Checklist

- Not all of these items are applicable to all PRs, the author should update this template to only leave the boxes in that are relevant
- Please make sure all these things are done and tick the boxes

```[tasklist]
- [x] Changes are OpenShift compatible
- [x] All added packages (via microdnf or otherwise) have a comment on why they are added
- [x] Add an entry to the CHANGELOG.md file
- [x] Integration tests ran successfully
```

<details>
<summary>TIP: Running integration tests with a new product image</summary>

The image can be built and uploaded to the kind cluster with the following commands:

```shell
bake --product <product> --image-version <stackable-image-version>
kind load docker-image <image-tagged-with-the-major-version> --name=<name-of-your-test-cluster>
```

See the output of `bake` to retrieve the image tag for `<image-tagged-with-the-major-version>`.
</details>

### CODE REVIEW

**Review by lfrancke — APPROVED** [review]

**Comment by lfrancke** [comment]
Do you think this "feature" is release noth worthy?

**Comment by siegfriedweber** [comment]
> Do you think this "feature" is release noth worthy?

Yes, I would think so. For customers using Azure, it could be important to know that this works.

**Comment by lfrancke** [comment]
In that case: Would you mind adding a small snippet that we can add to the releas notes (either as a comment or edit the description)?

**Comment by siegfriedweber** [comment]
> Would you mind adding a small snippet that we can add to the releas notes (either as a comment or edit the description)?

## Product features

* Apache HBase: The [hadoop-azure](https://hadoop.apache.org/docs/stable/hadoop-azure/) module was added to the image and is contained in the classpath. This makes it possible to use the [Azure Data Lake Storage Gen2 (ADLS)](https://azure.microsoft.com/en-us/products/storage/data-lake-storage/) instead of HDFS. See the [usage guide](https://docs.stackable.tech/home/24.11/hbase/usage-guide/adls) for detailed information.

**Pull request merged**
