### PR TITLE
feat: new stand-alone image for kcat

### PR DESCRIPTION
**Pull request by razvan**
# Description

Requirement for : https://github.com/stackabletech/kafka-operator/pull/677

This image is needed for the Kafka integration tests on OpenShift. The `edenhill/kcat` used initially doesn't work reliably on that platform.

The error is always:

```
│ %3|1709917514.507|FAIL|rdkafka#producer-1| [thrd:test-kafka.kuttl-test-shining-toucan.svc.cluster.local:9092/boo]: test-kafka.kuttl-test-shining-toucan.svc.cluster.local:9092/bootstrap: Failed to resolve 'test-kafka.kuttl-test-shining-toucan.svc.cluster.local:9092': Try again (after 5009ms in state CONNECT)                                                                                                         
│ % ERROR: Local: Host resolution failure: test-kafka.kuttl-test-shining-toucan.svc.cluster.local:9092/bootstrap: Failed to resolve 'test-kafka.kuttl-test-shining-toucan.svc.cluster.local:9092': Try again (after 5009ms in state CONNECT)                                                                                                                                                                                   
│ % ERROR: Local: All broker connections are down: 1/1 brokers are down: terminating 
```

Running the tests with our own kcat build succeeds.

This is not in `testing-tools` because that image is Debian based and we might want to reuse this binary in the Kafka image in the future.

## Definition of Done Checklist

- Not all of these items are applicable to all PRs, the author should update this template to only leave the boxes in that are relevant
- Please make sure all these things are done and tick the boxes
 
```[tasklist]
- [ ] Changes are OpenShift compatible
- [ ] All added packages (via microdnf or otherwise) have a comment on why they are added
- [ ] Things not downloaded from Red Hat repositories should be mirrored in the Stackable repository and downloaded from there
- [ ] All packages should have (if available) signatures/hashes verified
- [ ] Does your change affect an SBOM? Make sure to update all SBOMs
```

### CODE REVIEW

**Comment by sbernauer** [comment]
Sorry for the stupid question, but the kafka image already contains kcat (needed for health-checks), can't we used that in https://github.com/stackabletech/kafka-operator/pull/677?

**Comment by razvan** [comment]
> Sorry for the stupid question, but the kafka image already contains kcat (needed for health-checks), can't we used that in [stackabletech/kafka-operator#677](https://github.com/stackabletech/kafka-operator/pull/677)?

I tried. The tests also need `diff` and `cmp` which are not included in that image.

**Comment by lfrancke** [comment]
Should the image then maybe be named kafka-testing-tools?
But this is not a veto/blocker

**Comment by razvan** [comment]
> Should the image then maybe be named kafka-testing-tools? But this is not a veto/blocker

Done https://github.com/stackabletech/docker-images/pull/590/commits/f0aa734aeebf17d13b7bb549deec3d7aab0a38d9

**Review by adwk67 — APPROVED** [review]
lgtm, just one suggestion for consistency in image naming, but I'll leave that up to you.

**Pull request merged**
