### PR TITLE
fix: jq arg parsing

### PR DESCRIPTION
**Pull request by dervoeti**
The args to `jq` were not parsed correctly, which resulted in e.g.
```
...
"purl": "$purl",
...
```
in the final JSON of the SBOM.

I could not figure out how to concatenate the two args with `jq` (`$name` and `$description`) so I concatenated both variables with Shellscript into one arg for `jq`.

### CODE REVIEW

**Comment by razvan** [comment]
> I could not figure out how to concatenate the two args with `jq` (`$name` and `$description`) so I concatenated both variables with Shellscript into one arg for `jq`.

Have you tried [join()](https://jqlang.github.io/jq/manual/#join) ?

**Comment by dervoeti** [comment]
> > I could not figure out how to concatenate the two args with `jq` (`$name` and `$description`) so I concatenated both variables with Shellscript into one arg for `jq`.
> 
> Have you tried [join()](https://jqlang.github.io/jq/manual/#join) ?

Yeah, couldn't make it work. But I didn't try too much since joining the string with Shellscript works fine and shouldn't be a problem.

**Comment by NickLarsenNZ** [comment]
I have concatenated via `\($a\) \($b\)`, eg:

```
❯ jq -n --arg a hello --arg b world '"\($a) \($b)"'
"hello world"
```

**Review by NickLarsenNZ — APPROVED** [review]
LGTM. Left another comment on how to concat with `jq` for future reference.

**Pull request merged**
