### PR TITLE
HBase 2.4.18 support

### PR DESCRIPTION
**Pull request by lfrancke**
# Description

- Patches updated for new version
- Update dependencies for 2.4.18 to new patch dependencies where available
- Move to heredoc syntax
- Remove Log4Shell workarounds
- Add package_manifest
- Change upload script to only download & upload the sources and not the binaries

## Definition of Done Checklist

 
```[tasklist]
- [x] All added packages (via microdnf or otherwise) have a comment on why they are added
- [x] Things not downloaded from Red Hat repositories should be mirrored in the Stackable repository and downloaded from there
- [x] All packages should have (if available) signatures/hashes verified
- [x] Add an entry to the CHANGELOG.md file
- [x] Integration tests ran successfully
```

### CODE REVIEW

**Comment by siegfriedweber** [comment]
https://ci.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/hbase-operator-it-custom/160/

**Review by razvan — APPROVED** [review]

**Comment by lfrancke** [comment]
Closing in favor of #701

**Comment by lfrancke** [comment]
Reopening as the other PR has more issues to fix

**Review by razvan — APPROVED** [review]
lgtm

**Pull request merged**
