### PR TITLE
fix(java-base): Add needed tzdata-java package

### PR DESCRIPTION
**Pull request by sbernauer**
# Description

Nightly tests failed because of this

## Definition of Done Checklist

- Not all of these items are applicable to all PRs, the author should update this template to only leave the boxes in that are relevant
- Please make sure all these things are done and tick the boxes
 
```[tasklist]
- [x] Changes are OpenShift compatible
- [x] All added packages (via microdnf or otherwise) have a comment on why they are added
- [x] Things not downloaded from Red Hat repositories should be mirrored in the Stackable repository and downloaded from there
- [x] All packages should have (if available) signatures/hashes verified
- [x] Does your change affect an SBOM? Make sure to update all SBOMs
```

### CODE REVIEW

**Review by Jimvin — APPROVED** [review]
LGTM

**Comment by sbernauer** [comment]
Waiting for @lfrancke's approval

**Review by soenkeliebau — APPROVED** [review]
Lgtm

I have checked the checkboxes as well:

- OpenShift compatbile - no reason why it wouldn't be, package gets installed into ubi8 from redhat repos ..
- Checksums verified - done by microdnf during installation I believe
- SBOM updated - there is no sbom to update yet

**Review by lfrancke — APPROVED** [review]

**Comment by sbernauer** [comment]
Thanks!

**Pull request merged**
