### PR TITLE
Switch from 1.1.0 to 1.4.0 of the OPA Kafka plugin for most Kafka ver…

### PR DESCRIPTION
**Pull request by razvan**
…sions.

### CODE REVIEW

**Comment by teozkr** [comment]
Have you tested that the new combinations work? Can't seem to find an official version support matrix on their GH repo or website.

**Comment by maltesander** [comment]
> Have you tested that the new combinations work? Can't seem to find an official version support matrix on their GH repo or website.

From what i see here https://github.com/anderseknert/opa-kafka-plugin any version >= 1.0.0 was tested with kafka 2.7 or higher. Not sure what we do with 2.6 then?

**Comment by teozkr** [comment]
Ah, fair point, missed that bit.

**Review by maltesander — APPROVED** [review]
LGTM.

**Review by maltesander — APPROVED** [review]
LGTM.

**Pull request merged**
