### PR TITLE
chore: Bump opa-bundle-builder

### PR DESCRIPTION
**Pull request by NickLarsenNZ**
# Description

Bump opa-bundle-builder with updated dependencies from https://github.com/stackabletech/opa-bundle-builder/pull/20

## Definition of Done Checklist

- Not all of these items are applicable to all PRs, the author should update this template to only leave the boxes in that are relevant
- Please make sure all these things are done and tick the boxes
 
```[tasklist]
- [ ] Changes are OpenShift compatible
- [ ] All added packages (via microdnf or otherwise) have a comment on why they are added
- [ ] Things not downloaded from Red Hat repositories should be mirrored in the Stackable repository and downloaded from there
- [ ] All packages should have (if available) signatures/hashes verified
- [ ] Does your change affect an SBOM? Make sure to update all SBOMs
- [ ] Add an entry to the CHANGELOG.md file
- [ ] Integration tests ran successfully
```

<details>
<summary>TIP: Running integration tests with a new product image</summary>

The image can be built and uploaded to the kind cluster with the following commands:

```shell
bake --product <product> --image-version <stackable-image-version>
kind load docker-image <image-tagged-with-the-major-version> --name=<name-of-your-test-cluster>
```

See the output of `bake` to retrieve the image tag for `<image-tagged-with-the-major-version>`.
</details>

### CODE REVIEW

**Comment by NickLarsenNZ** [comment]
Unsure if I was supposed to add new entries for `1.1.2`, and keep the `1.1.1` version.

**Review by sbernauer — APPROVED** [review]
I assume this build locally. We need to swap out 1.1.1 with 1.1.2, as the OPA image can only pull a single version ;)

**Comment by NickLarsenNZ** [comment]
I haven't tested the build locally, but can do later. I will not merge it until tested.

**Comment by sbernauer** [comment]
Build worked for me
```
 => [opa-0_57_0] exporting to image                                                                                                                                                                           0.7s
 => => exporting layers                                                                                                                                                                                       0.7s
 => => writing image sha256:6ee75bd5036532152c5887c932ffcb635d77ceca1fa90e043787347f0c927a43                                                                                                                  0.0s
 => => naming to docker.stackable.tech/stackable/opa:0.57.0-stackable0.0.0-dev                                                                                                                                0.0s
 => [opa-0_61_0] exporting to image                                                                                                                                                                           0.7s
 => => exporting layers                                                                                                                                                                                       0.7s
 => => writing image sha256:22138a6a7aa0055f4d35fc6463259bda485964b2d77e60b77bb832ae31a983e1                                                                                                                  0.0s
 => => naming to docker.stackable.tech/stackable/opa:0.61.0-stackable0.0.0-dev 
```

**Pull request merged**
