### PR TITLE
Install cargo-cyclonedx and cargo-auditable and copy a bom.xml if it exists

### PR DESCRIPTION
**Pull request by lfrancke**
This is the first step towards having SBOMs in CycloneDX format (version 1.3 at the moment) for our operators.

### CODE REVIEW

**Review by sbernauer — APPROVED** [review]
Tested with trino. We might need to test some exotic ones, such as secret-op
```
docker run -it --entrypoint bash docker.stackable.tech/stackable/trino-operator:0.0.0-dev -c 'ls -la /usr/local/bin/'
total 22808
drwxr-xr-x 1 root root     4096 Jun 15 10:51 .
drwxr-xr-x 1 root root     4096 May  3 15:07 ..
-rw-r--r-- 1 root root    10758 Jun 15 10:51 bom.xml
-rwxr-xr-x 1 root root 23327992 Jun 15 10:51 stackable-trino-operator
```

**Comment by lfrancke** [comment]
Thanks! I probably will want to change this PR again. So I won't commit it just yet.

**Review by sbernauer — APPROVED** [review]
```
docker run -it --entrypoint bash docker.stackable.tech/stackable/hdfs-operator:0.0.0-dev -c 'ls -la /usr/local/bin/'
total 25000
drwxr-xr-x 1 root root     4096 Jun 16 06:52 .
drwxr-xr-x 1 root root     4096 May  3 15:07 ..
-rwxr-xr-x 1 root root 25399416 Jun 16 06:51 stackable-hdfs-operator
-rw-r--r-- 1 root root   181890 Jun 16 06:51 stackable-hdfs-operator.cdx.xml
```

**Comment by lfrancke** [comment]
Thank you. I'll wait with merging until I've had the chance to test it with the secret operator

**Comment by sbernauer** [comment]
Guess what I did (just took time)
```
docker run -it --entrypoint bash docker.stackable.tech/stackable/secret-operator:0.0.0-dev -c 'ls -la /usr/local/bin/'
total 34436
drwxr-xr-x 1 root root     4096 Jun 16 07:05 .
drwxr-xr-x 1 root root     4096 May  3 15:07 ..
-rwxr-xr-x 1 root root 12611480 Jun 16 07:05 stackable-krb5-provision-keytab
-rw-r--r-- 1 root root   221503 Jun 16 07:05 stackable-krb5-provision-keytab.cdx.xml
-rwxr-xr-x 1 root root 22186768 Jun 16 07:05 stackable-secret-operator
-rw-r--r-- 1 root root   221491 Jun 16 07:05 stackable-secret-operator.cdx.xml
```

**Pull request merged**
