### PR TITLE
Release multi-arch images

### PR DESCRIPTION
**Pull request by sbernauer**
# Description

Not tested yet. Given this is mostly copy/past we could argue it's not worth it pointing it to stackable-experimental, running it with a bogus version, clean up all the images again and revert the bogus change.
Additionally, currently the build is broken because of building Hive from source missing packages on ARM (https://issues.apache.org/jira/browse/HIVE-21939)

## Definition of Done Checklist

- Not all of these items are applicable to all PRs, the author should update this template to only leave the boxes in that are relevant
- Please make sure all these things are done and tick the boxes
 
```[tasklist]
- [ ] Changes are OpenShift compatible
- [ ] All added packages (via microdnf or otherwise) have a comment on why they are added
- [ ] Things not downloaded from Red Hat repositories should be mirrored in the Stackable repository and downloaded from there
- [ ] All packages should have (if available) signatures/hashes verified
- [ ] Does your change affect an SBOM? Make sure to update all SBOMs
- [ ] Add an entry to the CHANGELOG.md file
- [ ] Integration tests ran successfully
```

<details>
<summary>TIP: Running integration tests with a new product image</summary>

The image can be built and uploaded to the kind cluster with the following commands:

```shell
bake --product <product> --image-version <stackable-image-version>
kind load docker-image <image-tagged-with-the-major-version> --name=<name-of-your-test-cluster>
```

See the output of `bake` to retrieve the image tag for `<image-tagged-with-the-major-version>`.
</details>

### CODE REVIEW

**Review by Maleware — COMMENTED** [review]
Please add a changelog entry. Other than that, awesome! :)

**Review by Maleware — APPROVED** [review]
Still LGTM ;)

**Comment by sbernauer** [comment]
I'm not aware of any documentation but maybe @Maleware knows better. We only worked on the build process, for the customer nothing should change (it's just that docker manifest now supports multi-arch).
Starting with 24.7 it "just works" (tm) on ARM, I wouldn't know what to document

**Comment by maltesander** [comment]
We mentioned it in the release docs (https://docs.stackable.tech/home/stable/release-notes.html) and point to experimental docs here https://docs.stackable.tech/home/stable/concepts/arm64-support @lfrancke

**Comment by sbernauer** [comment]
@maltesander just FYI this work here enables us to get rid of https://docs.stackable.tech/home/stable/concepts/arm64-support.
This is the proper solution to include it in the SDP, no special repo, opt in or anything else is needed in 24.7. any more :rocket:

**Comment by Maleware** [comment]
Yeah we didn't document consumer facing as this is going to be abstracted away by the method we use. As Malte said, we give instructions on how to early access this feature and as Sebastian mentioned, the customer won't need to do anything anymore past 24.7.

**Comment by lfrancke** [comment]
Thank you. Did we then _delete_ the experimental page?
And we should definitely document somewhere the supported platforms.
x86 is kinda given but we should have some way to document that we also support ARM.

Do we have this?
If not I'd like to see a follow-up ticket

**Comment by Maleware** [comment]
Great Idea, no we didn't deprecate any documentation till as we are not ready. 

I like the idea of having supported architectures listed somewhere I created an [issue](https://github.com/stackabletech/issues/issues/577) in the [arm64 epic](https://github.com/stackabletech/issues/issues/463)

**Comment by lfrancke** [comment]
I am a bit confused still

> This is the proper solution to include it in the SDP, no special repo, opt in or anything else is needed in 24.7. any more 🚀

> Great Idea, no we didn't deprecate any documentation till as we are not ready.

Anyway: I have added a task to  https://github.com/stackabletech/issues/issues/577 to remove the old stuff as well.

**Comment by sbernauer** [comment]
> Did we then delete the experimental page?

We can not delete the only docs on arm support (which is based on 24.3), simply because 24.7 is not released yet.
One we released 24.7 we can remove the intermediate docs (based on 24.3)

**Pull request merged**
