### PR TITLE
ci: Use stackabletech/actions repo

### PR DESCRIPTION
**Pull request by Techassi**
This PR updates all workflows to use the https://github.com/stackabletech/actions repo instead of local actions.

### CODE REVIEW

**Review by NickLarsenNZ — DISMISSED** [review]
LGTM, a couple of things to note:

- Maybe hold off on the merge until the end of the day (since it will consume a lot of runners). Or at least let everyone know that it is happening so they can work around it.
- I wonder if Renovate can raise PRs when there is a new commit hash in the actions repo.

**Comment by Techassi** [comment]
> Maybe hold off on the merge until the end of the day (since it will consume a lot of runners). Or at least let everyone know that it is happening so they can work around it.

Yeah that makes sense. Will do so.

> I wonder if Renovate can raise PRs when there is a new commit hash in the actions repo.

I'm no Renovate expert, so I don't know. Maybe @lfrancke knows more about it.

**Review by NickLarsenNZ — COMMENTED** [review]
LGTM

**Review by NickLarsenNZ — DISMISSED** [review]

**Comment by lfrancke** [comment]
I want all new things we merge to be auto updatable. If you're not sure it can be please hold off. I don't have time to look today.

**Comment by Techassi** [comment]
So we can support Renovate by adding tags to the https://github.com/stackabletech/actions repo, according to [these](https://docs.renovatebot.com/modules/manager/github-actions/#supported-datasources) supported data sources.

**Comment by NickLarsenNZ** [comment]
> So we can support Renovate by adding tags to the https://github.com/stackabletech/actions repo, according to [these](https://docs.renovatebot.com/modules/manager/github-actions/#supported-datasources) supported data sources.
> 
> I can add an initial tag (e.g. `0.0.1`) to enable support right now.

I thought Renovate could also do commit hash updates too :shrug:

**Review by NickLarsenNZ — APPROVED** [review]
LGTM

**Comment by Techassi** [comment]
> > So we can support Renovate by adding tags to the [stackabletech/actions](https://github.com/stackabletech/actions) repo, according to [these](https://docs.renovatebot.com/modules/manager/github-actions/#supported-datasources) supported data sources.
> > I can add an initial tag (e.g. `0.0.1`) to enable support right now.
> 
> I thought Renovate could also do commit hash updates too 🤷

It can update the commit hash, but it needs a git tag to be present. For example: Currently, the tag `0.0.1` points to [`93b2a5a023487ef9509f24600c12374553478f1d`](https://github.com/stackabletech/actions/commit/93b2a5a023487ef9509f24600c12374553478f1d). Once we add a new tag `0.0.2` which will for example point to `1234abcd`, Renovate will use that commit hash.

**Comment by lfrancke** [comment]
Shall we try that next week?

**Comment by Techassi** [comment]
> Shall we try that next week?

Sure, we can do that.

**Comment by lfrancke** [comment]
I just tried to run renovate, but:

```
Renovate failed to look up the following dependencies: Can't find version matching 0.0.1 for github-tags package stackabletech/actions,
```

See the [Dependency Dashboard](https://github.com/stackabletech/docker-images/issues/672) (this might change hence the screenshot & extract)

image

**Comment by lfrancke** [comment]
I'm sure it's documented _somewhere_ and I'm sure it can be configured.
But: The tag & release need to be prepended with a "v". So it needs to be v0.0.1, v0.0.2

If anyone wants to google for it later look for "applyDatasourceFilters (datasource/index.ts)" and "applyExtractVersion" and the "extractVersion" regex in renovate.

**Comment by Techassi** [comment]
> I'm sure it's documented somewhere and I'm sure it can be configured.
But: The tag & release need to be prepended with a "v". So it needs to be v0.0.1, v0.0.2

Well, then the following section in the docs is clearly a lie:

> The GitHub tag is in the format of (prefix-)(v)1.0.0, where prefix and v are optional and 1.0.0 is the version number. Here are the examples of valid GitHub tags: 1.0.1, 1.0, 1, v1.0.1, v1.0
>
> _Taken from [here](https://docs.renovatebot.com/modules/manager/github-actions/#additional-information)_

It might be worth to fix this upstream then?

**Pull request merged**
