### PR TITLE
feat(trino 428): Switch to patched storage connector

### PR DESCRIPTION
**Pull request by sbernauer**
# Description

So far we pulled in [trino-storage](https://github.com/snowlift/trino-storage) from https://github.com/snowlift/trino-storage/releases/tag/v428.
This PR switched to a version with backports made in https://github.com/snowlift/trino-storage/pull/244, https://github.com/snowlift/trino-storage/pull/241 and https://github.com/snowlift/trino-storage/pull/240, as they are needed for a customer.

trino-storage 432 contains the fixes, so long-term we can get rid of a patched version again. 

CC @Maleware @soenkeliebau @maltesander  

## Definition of Done Checklist

- Not all of these items are applicable to all PRs, the author should update this template to only leave the boxes in that are relevant
- Please make sure all these things are done and tick the boxes
 
```[tasklist]
- [ ] Changes are OpenShift compatible
- [ ] All added packages (via microdnf or otherwise) have a comment on why they are added
- [ ] Things not downloaded from Red Hat repositories should be mirrored in the Stackable repository and downloaded from there
- [ ] All packages should have (if available) signatures/hashes verified
- [ ] Does your change affect an SBOM? Make sure to update all SBOMs
```

### CODE REVIEW

**Review by soenkeliebau — APPROVED** [review]
The 428-jackson version was built by checking out the main branch of the snowlift trino connector and compiling it against the Trino deps in version 428.
We have not created a proper build chain for it, as this will be a one time effort hopefully.

**Comment by lfrancke** [comment]
And we uploaded that to Nexus?
Can we please put a README next to it saying as much including information about any licenses?

**Comment by sbernauer** [comment]
FYI, it's in https://repo.stackable.tech/#browse/browse:packages:trino-storage and there is a readme

**Comment by soenkeliebau** [comment]
I have pushed the exact code I built to our fork, tagged it and added a brief section to the Readme: https://repo.stackable.tech/repository/packages/trino-storage/README.md

**Comment by maltesander** [comment]
as discussed with @soenkeliebau, merging this.

**Pull request merged**
