### PR TITLE
feat(omid): include examples to simplify testing

### PR DESCRIPTION
**Pull request by razvan**
# Description

Required for: https://github.com/stackabletech/hbase-operator/pull/515

## Definition of Done Checklist

- Not all of these items are applicable to all PRs, the author should update this template to only leave the boxes in that are relevant
- Please make sure all these things are done and tick the boxes
 
```[tasklist]
- [ ] Changes are OpenShift compatible
- [ ] All added packages (via microdnf or otherwise) have a comment on why they are added
- [ ] Things not downloaded from Red Hat repositories should be mirrored in the Stackable repository and downloaded from there
- [ ] All packages should have (if available) signatures/hashes verified
- [ ] Add an entry to the CHANGELOG.md file
- [ ] Integration tests ran successfully
```

<details>
<summary>TIP: Running integration tests with a new product image</summary>

The image can be built and uploaded to the kind cluster with the following commands:

```shell
bake --product <product> --image-version <stackable-image-version>
kind load docker-image <image-tagged-with-the-major-version> --name=<name-of-your-test-cluster>
```

See the output of `bake` to retrieve the image tag for `<image-tagged-with-the-major-version>`.
</details>

### CODE REVIEW

**Comment by lfrancke** [comment]
What do these examples contain? 

If they are "just" omid code we're probably fine but if they contain new dependencies etc. we should check with @dervoeti if they contain many new vulnerabilities.

**Comment by razvan** [comment]
> What do these examples contain?

They have the same deps as the TSO server it's self : https://github.com/apache/phoenix-omid/blob/1.1.0/examples/pom.xml

**Comment by dervoeti** [comment]
Yep, the numbers are the same:
image

I also checked some vulnerabilities in the examples and they were, as @razvan mentioned, already present in the TSO server.

**Review by dervoeti — APPROVED** [review]
LGTM

**Pull request merged**
